### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by MoAlyousef** [osen/Fl_Flow#2]
Hello

Thanks for your work on layouts with FLTK. I’m currently using Fl_Flex and also have a wrapper for it in Rust. It works great 👍 

Would you mind adding a license to this library as well. 

Thanks again

**Comment by MoAlyousef** [comment]
I just saw from the fltk.general thread that this is considered for inclusion in FLTK. That’s great. I’ll close this issue.

**Comment by osen** [comment]
Hi there.

Yes, we hopefully plan to get it included with upstream FLTK once a few changes have been made. Then it will be released under the same LGPL license.

Thanks
